<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Slider routes...
Route::resource('slider', 'SliderController');
// PageCategory routes...
Route::resource('page-category', 'PageCategoryController');
// Page routes...
Route::resource('page', 'PageController');
// ContentCategory routes...
Route::resource('content-category', 'ContentCategoryController');
// Content routes...
Route::resource('content', 'ContentController');
// ArticleCategory routes...
Route::resource('article-category', 'ArticleCategoryController');
// Article routes...
Route::resource('article', 'ArticleController');
// events routes...
Route::resource('event', 'EventController');
// Faq routes...
Route::resource('faq', 'FaqController');
// Testimonial routes...
Route::resource('testimonial', 'TestimonialController');
// CommitteeCategory routes...
Route::resource('committee-category', 'CommitteeCategoryController');
// CommitteeMember routes...
Route::resource('committee-member', 'CommitteeMemberController');
// Form routes...
Route::resource('form', 'FormController');
