<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


// User routes...
Route::resource('user', 'UserController');
// User profile routes
Route::prefix('profile')->name('profile-')->group(function () {
    // UserAccountInfo routes...
    Route::resource('account-info', 'Profile\AccountInfoController');
    // UserPersonalInfo routes...
    Route::resource('personal-info', 'Profile\PersonalInfoController')->only(['index', 'update']);
    // UserResidentialInfo routes...
    Route::resource('residential-info', 'Profile\ResidentialInfoController')->only(['index', 'update']);
    // UserEducationalInfo routes...
    Route::resource('educational-info', 'Profile\EducationalInfoController');
    // UserWorkInfo routes...
    Route::resource('work-info', 'Profile\WorkInfoController');
    // UserSkillInfo routes...
    Route::resource('skill', 'Profile\SkillController');
    // UserLanguage routes...
    Route::resource('language', 'Profile\LanguageController');
    // UserInterest routes...
    Route::resource('interest', 'Profile\InterestController');
    // SocialAccount routes
    Route::resource('social-account', 'Profile\SocialAccountController');
    // ChangePassword routes...
    Route::resource('password-change', 'Profile\PasswordChangeController');
});
// Role routes...
Route::resource('role', 'RoleController');
// Permission routes...
Route::resource('permission', 'PermissionController');
// Dashboard routes...
Route::resource('dashboard', 'DashboardController');
// batch routes...
Route::resource('batch', 'BatchController');
// academic session routes...
Route::resource('academic-session', 'AcademicSessionController');
// registration routes...
Route::resource('registration', 'RegistrationController');
